// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUxsktUOKO-sNFJnhaNYua6So1fmGk3CM',
    appId: '1:183432795185:web:f8f85d33e050c3413a3110',
    messagingSenderId: '183432795185',
    projectId: 'fir-auth-1f0a3',
    authDomain: 'fir-auth-1f0a3.firebaseapp.com',
    storageBucket: 'fir-auth-1f0a3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPY_hkGPWyZyDu5N8ygc0Oh_dCzu9Vgf8',
    appId: '1:183432795185:android:531deb8fc317221a3a3110',
    messagingSenderId: '183432795185',
    projectId: 'fir-auth-1f0a3',
    storageBucket: 'fir-auth-1f0a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdc02OT3E2RUhKbn6U3Sc0oxP9w98JBSU',
    appId: '1:183432795185:ios:c8a733319ee8f3793a3110',
    messagingSenderId: '183432795185',
    projectId: 'fir-auth-1f0a3',
    storageBucket: 'fir-auth-1f0a3.appspot.com',
    iosBundleId: 'com.example.authApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdc02OT3E2RUhKbn6U3Sc0oxP9w98JBSU',
    appId: '1:183432795185:ios:c8a733319ee8f3793a3110',
    messagingSenderId: '183432795185',
    projectId: 'fir-auth-1f0a3',
    storageBucket: 'fir-auth-1f0a3.appspot.com',
    iosBundleId: 'com.example.authApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUxsktUOKO-sNFJnhaNYua6So1fmGk3CM',
    appId: '1:183432795185:web:0a0e16910017a9603a3110',
    messagingSenderId: '183432795185',
    projectId: 'fir-auth-1f0a3',
    authDomain: 'fir-auth-1f0a3.firebaseapp.com',
    storageBucket: 'fir-auth-1f0a3.appspot.com',
  );
}
